### ISSUE TITLE
strange error with -lib in file hxml

### ISSUE THREAD

**Issue by francescoagati** [jasononeil/webpack-haxe-loader#12]
in my file build.hxml i use -lib haxe-loader  tink_macro
and webpack responds with 
```
Error: Command failed:  custom-haxe /haxe/bin/haxe -D webpack_namespace=build -main Main -js /tmp/tmp-64300cUH1nRB8u9JA.js -lib haxe-loader  tink_macro -cp . -cp custom-haxe/haxe/.haxelib/ -dce full -D analyzer -D analyzer-module
--macro:1: character 0 : Invalid package : tink_macro.0,12,0.src.tink should be tink

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

i have change the path of haxe in the package haxe-loader for using a custom version of haxe. but the file directory of haxelib and tino macro are founded normally. what is strange is this  tink_macro.0,12,0.src.tink should be tink

**Comment by francescoagati** [comment]
ok resolved
in file .hxml the importa is create a -lib line for each library
so instead of -lib haxe-loader thx.core
need do
-lib haxe-loader
-lib thx.core
