### ISSUE TITLE
Cannot compile with JQueryExtern ?

### ISSUE THREAD

**Issue by zabojad** [jasononeil/webpack-haxe-loader#13]
I added a JQuery plugin to my project and cannot compile it with webpack anymore:
```
ERROR in ./build-web.hxml
Module build failed: Error: Command failed: haxe -D webpack_namespace=build-web -main myproject.Boot -js /var/folders/mc/2kyt0cbn12d95zcg5wzb0sj80000gn/T/tmp-27658ASWQrmYgRRyM.js -cp src -lib js-kit -lib haxe-loader -lib react -lib react-addons -lib jQueryExtern -lib devextreme -debug --macro js.jquery.Config.setNative('jQuery') --macro js.jquery.Config.addPlugin('js.html.devexpress.DevExpress')
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `haxe -D webpack_namespace=build-web -main myproject.Boot -js /var/folders/mc/2kyt0cbn12d95zcg5wzb0sj80000gn/T/tmp-27658ASWQrmYgRRyM.js -cp src -lib js-kit -lib haxe-loader -lib react -lib react-addons -lib jQueryExtern -lib devextreme -debug --macro js.jquery.Config.setNative('jQuery') --macro js.jquery.Config.addPlugin('js.html.devexpress.DevExpress')'

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./build-web.hxml
webpack: Failed to compile.
```

while the classic haxe compilation works:
```
$ haxe build-web.hxml 
$ 
```

Here is my `build-web.hxml`:
```
-main myproject.Boot
-js app/myproject.js
-cp src
# -lib thx.core
-lib js-kit
-lib haxe-loader
-lib react
-lib react-addons
-lib jQueryExtern
-lib devextreme
# generates the .js.map file + diverse other debug features (redux-logger) + [haxe-react not inline cmps](https://github.com/massiveinteractive/haxe-react#inline-reactelements)
-debug
# uncomment the following to disable traces
#--no-traces
--macro js.jquery.Config.setNative('jQuery')
--macro js.jquery.Config.addPlugin('js.html.devexpress.DevExpress')
```

**Comment by zabojad** [comment]
@elsassph @jasononeil any idea?

**Comment by zabojad** [comment]
OK, solution found. I just needed to put the macro arguments between double quotes like this:
```
-main myproject.Boot
-js app/myproject.js
-cp src
# -lib thx.core
-lib js-kit
-lib haxe-loader
-lib react
-lib react-addons
-lib jQueryExtern
-lib devextreme
# generates the .js.map file + diverse other debug features (redux-logger) + [haxe-react not inline cmps](https://github.com/massiveinteractive/haxe-react#inline-reactelements)
-debug
# uncomment the following to disable traces
#--no-traces
--macro "js.jquery.Config.setNative('jQuery')"
--macro "js.jquery.Config.addPlugin('js.html.devexpress.DevExpress')"
```

**Comment by elsassph** [comment]
Oho I've had this problem in the past.

**Comment by kLabz** [comment]
@zabojad that's now handled thanks to #29 :) (not released yet, and may have a more robust solution implemented later)
